# Generated by Django 5.1.4 on 2025-02-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='img',
            new_name='imagen',
        ),
    ]
